#!/bin/bash

# Function to check if a number is prime
is_prime() {
    num="$1"
    if [ "$num" -le 1 ]; then
        return 1
    fi
    for ((i = 2; i * i <= num; i++)); do
        if [ "$((num % i))" -eq 0 ]; then
            return 1
        fi
    done
    return 0
}

awk '{
    i = 1
    while (i <= length($0)) {
        char = substr($0, i, 1)
        if (char ~ /[0-9]/) {
            digit_str = char
            while ((i + 1) <= length($0) && substr($0, i + 1, 1) ~ /[0-9]/) {
                digit_str = digit_str substr($0, i + 1, 1)
                i++
            }

            # Add the digit_str to the numbers array
            numbers[digit_str] = 1
        }
        i++
    }
}
END {
    # Print the contents of the numbers array
    for (number in numbers) {
        print number
    }
}' $1 |

# Check each command-line argument
while read arg; do
    if is_prime "$arg"; then
        echo $arg
    fi
done
